(feat): add functions that get called to setup the infra project
Signed-off-by: quophyie <quophyie@yahoo.com>

diff --git a/scripts-infra/bin/setup b/scripts-infra/bin/setup
--- a/scripts-infra/bin/setup
+++ b/scripts-infra/bin/setup
@@ -1,63 +1,35 @@
 #!/usr/bin/env bash
 
-# Please Use Google Shell Style: https://google.github.io/styleguide/shell.xml
+# shared quantal infra functions
+INFRA_SHARED_FUNCS_DIR="$( cd "$(dirname "$0")"/.. >/dev/null 2>&1 ; pwd -P )"
+INFRA_SHARED_FUNCS=${INFRA_SHARED_FUNCS_DIR}/shared_infra_funcs.sh
 
-# ---- Start unofficial bash strict mode boilerplate
-# http://redsymbol.net/articles/unofficial-bash-strict-mode/
-set -o errexit  # always exit on error
-set -o errtrace # trap errors in functions as well
-set -o pipefail # don't ignore exit codes when piping output
-set -o posix    # more strict failures in subshells
-# set -x          # enable debugging
+set -e
+# Naive try catch
+{
+ source ${INFRA_SHARED_FUNCS}
+} ||
+{
 
-IFS="$(printf "\n\t")"
-# ---- End unofficial bash strict mode boilerplate
+ echo "Quantal shared scripts not found!"
+ exit 1
 
-cd "$(dirname "${BASH_SOURCE[0]}")/.."
-env_file=./.env
-
-function main() {
-  set -e
-
-  add_new_env_vars
 }
 
-function file_ends_with_newline() {
-  [[ $(tail -c1 "${env_file}" | wc -l) -gt 0 ]]
-}
+check_quantal_shared_scripts_dir_exists
+configure_infra_scripts_dir_env_var
+update_profile_with_aliases_source
 
-function add_new_env_vars() {
-  # create .env and set perms if it does not exist
-  [[ ! -f "${env_file}" ]] && {
-    touch "${env_file}"
-    chmod 0600 "${env_file}"
-  }
+PROFILE_FILE=
+get_profile_file PROFILE_FILE
 
-  # if the file does not end with new line add a new line to it
-  if ! file_ends_with_newline; then
-    echo "" >> "${env_file}"
-  fi
+printf "\n\n"
+echo "Please source file ${PROFILE_FILE} to complete the setup"
+echo ""
+echo "*****************************"
+echo "!!! PLEASE COPY AND RUN COMMAND BELOW TO COMPLETE SETUP !!!"
+echo ""
+echo "source ${PROFILE_FILE}"
+printf "\n\n"
 
-  find . -name .env.example -type f -print0 |
-    (xargs -0 grep -Ehv '^\s*#' || true) |
-    sort |
-    {
-      while IFS= read -r var; do
-        if [[ -z "${var}" ]]; then
-          continue
-        fi
-        key="${var%%=*}" # get var key
-        # only eval for dynamic vars if the value has a dollar sign
-        if [[ "${var}" =~ "$" ]]; then
-          var="$(eval echo "${var}")" # generate dynamic values
-        fi
-        # If .env doesn't contain this env key, add it
-        if ! grep -qLE "^${key}=" "${env_file}"; then
-          echo "Adding $key to .env"
-          echo "$var" >>"${env_file}"
-        fi
-      done
-    }
-}
-
-main
+# main
